title: Single cell analysis course repository
description: >- # this means to ignore newlines until "baseurl:"
  Course repository and website for the single cell analysis course WS2021/22.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ies-helmholtzzentrummunchen.github.io/single-cell-analysis-course-2022/" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Europe/Berlin
collections:
  01_lectures:
    title: true
    date: true
    end: true
    location: false
    output: true
  02_homework:
    title: true
    date: true
    output: true
  04_literature:
    title: true
    output: true
  03_talks:
    title: true
    output: true
  05_interactive:
    title: true
    output: true
  06_schedule:
    title: true
    output: true
defaults:
  -
    scope:
      path: ""
      type: "01_lectures"
    values:
      layout: "lecture"
  -
    scope:
      path: ""
      type: "02_talks"
    values:
      layout: "lecture"
  -
    scope:
      path: ""
      type: "04_literature"
    values:
      layout: "code"
  -
    scope:
      path: ""
      type: "05_interactive"
    values:
      layout: "code"
  -
    scope:
      path: ""
      type: "03_homework"
    values:
      layout: "code"
  -
    scope:
      path: ""
      type: "other"
    values:
      layout: "code"
  -
    scope:
      path: ""
      type: "06_schedule"
    values:
      layout: "code"
